<a href="https://colab.research.google.com/github/Cubit0-de-hielo/cubito/blob/main/clase_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #para usar np hay que poner la bibliotea
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:6])
print(arr[4:]) #se imprime d ese numero en adelate
print(arr[-3:-1])
print(arr[-1]) #los numeros negativo funcionana como ls positivos pero a  la inversa
print(arr[1:5:2])
print(arr[::2]) #para ir de dos en dos
print(arr[0:]) #toda la sucecion
print(arr[:0]) #imprimetodo lo anterior a x numero

[2 3 4 5 6]
[5 6 7]
[5 6]
7
[2 4]
[1 3 5 7]
[1 2 3 4 5 6 7]
[]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, ::]) #aqui se especifica lalista y los numeros a elejir
print(arr[0:1, 2])
print(arr[0:6, 2])
print(arr[0:2, 3])
print(arr[0,4])

[ 6  7  8  9 10]
[3]
[3 8]
[4 9]
5


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])
print(arr[0:1, 2:5])

[[2 3 4]
 [7 8 9]]
[[3 4 5]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x) #imprime indices no numeros

(array([3, 5, 6]),)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [ ]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [ ]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [ ]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [ ]:
suma=x+y
print(f"la suma es {suma}")

la suma es [5 7 9]


In [ ]:
resta=y-x
print(f"la resta es {resta}")

la resta es [3 3 3]


In [ ]:
multiplicacion=y*x
print(f"la multiplicacion es {multiplicacion}")

la multiplicacion es [ 4 10 18]


In [ ]:
division=y/x
print(f"la division es {division}")

la division es [4.  2.5 2. ]


In [ ]:
print(f"numero pi= {np.pi}")

numero pi= 3.141592653589793


In [ ]:
x=np.array (list(range(1,9)))
print(x)

[1 2 3 4 5 6 7 8]


In [ ]:
x.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
x.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [ ]:
x.reshape(-1,1).shape

(8, 1)

In [ ]:
x=np.linspace(0,1,2)
x

array([0., 1.])

In [ ]:
np.random.uniform(0,1,6)

array([0.43744733, 0.79064351, 0.58468643, 0.76465206, 0.1018212 ,
       0.66677705])

In [ ]:
y=4
z = np.random.randint(0,10,size=1)
if y == z:
print(logrado)
#lo terminere de tarea