<a href="https://colab.research.google.com/github/Cubit0-de-hielo/cubito/blob/main/clase_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#funciona igal con [] y con (), pero se recomiencda utilizar mas los []
arr1 = np.array((1, 2, 3, 4, 5))

print(arr1)

print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#2D (cuadrado)
#np ayuda a ver de mejor forma las matrices
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3D (cubo)
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
#nnumero de lementos
c = np.array([[1, 2, 3], [4, 5, 6]])
#numero de listas y numero e elements generlal de cada lista
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
#numero de listas de listas; numero de listas en cada lista y numero general de elementos en cada lista

print(a.ndim,a.shape)
print(b.ndim,b.shape)
print(c.ndim,c.shape)
print(d.ndim,d.shape)

0 ()
1 (5,)
2 (2, 3)
3 (2, 2, 3)


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2do elemento de la 1er Fila: ', arr[1, 0])

2do elemento de la 1er Fila:  6


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [ ]:
m = np.array ([[1,2,3,],[4,5,6],[7,8,9]])
sum = np.sum(m)
print(sum)

45


In [ ]:
v_1 = np.array ([1,2,3])
v_2 = np.array ([4,5,6])
prod = np.dot(v_1,v_2)
print(prod)

32


In [ ]:
list1 = [1,1,1]
list2 = [1,1,1]
producto = sum(x*y for x, y in zip(list1,list2))
print(producto)

3
